services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 5s
      timeout: 5s
      retries: 20

  odoo:
    image: odoo:19.0
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./custom/addons:/mnt/extra-addons
      - ./odoo-docker.conf:/etc/odoo/odoo.conf:ro
    command:
      - odoo

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - odoo
    ports:
      - "8000:8000"
    environment:
      ODOO_URL: http://odoo:8069
      ODOO_DB: testovaya
      ODOO_USER: admin
      ODOO_PASSWORD: "}[Ub0({c1|3X8a3m6z?£EKd"
      API_TOKEN: super_secret_123

volumes:
  db-data:
  odoo-data:
